blockchain:
  - "🏷️Blockchain tech-stack"
devops:
  - "🏷️DevOps tech-stack"
e-commerce:
  - "🏷️e-commerce tech-stack"
e-gov:
  - "🏷️e-gov tech-stack"
game:
  - "🏷️Game tech-stack"
iot:
  - "🏷️IoT tech-stack"
ml:
  - "🏷️Machine learning & Artificial intelligence tech-stack"
mobile:
  - "🏷️Mobile tech-stack"
quantum:
  - "🏷️Quantum Computing tech-stack"
vr:
  - "🏷️Virtual/Augmented reality tech-stack"
web:
  - "🏷️Web tech-stack"
